apiVersion: apps/v1

kind: Deployment

metadata:
  name: myfrontend-replicaset
  labels:
    app: myapp-frontend
    type: frontend

spec:
  template:
    metadata:
      name: myfrontend-pod
      labels:
        app: myapp-frontend
        type: frontend

    spec:
      containers:
        - name: myfrontend-container
          image: ntguilty/weighted-average-frontend:latest
          stdin: true

  replicas: 3
  selector:
    matchLabels:
      type: frontend